
/*
* Function codes
*/

// Read commands
#define READ_ENCODER 0x30
#define READ_NUMBER_PULSES 0x33
#define READ_ERROR_SHAFT_ANGLE 0x39
#define READ_EN_STATUS 0x3A
#define RELEASE_SHAFT_LOCKED_ROTOR_PROTECTION_STATE 0x3D
#define READ_SHAFT_PROTECTION_STATE 0x3E

//Set commands
#define CALIBRATE 0x80
#define SET_MOTOR_TYPE 0x81
#define SET_WORK_MODE 0x82
#define SET_CURRENT 0x83
#define SET_SUBDIVISION 0x84
#define SET_ACTIVE_EN_PIN 0x85
#define SET_DIRECTION 0x86
#define SET_AUTO_SCREEN_TURNOFF 0x87
#define SET_MOTOR_SHAFT_LOCKED_ROTOR_PROTECTION 0x88
#define SET_SUBDIVISION_INTERPOLATION 0x89
#define SET_BAUDRATE 0x8A
#define SET_SLAVE_ADDRESS 0x8B
#define RESTORE_DEFAULT_PARAMETER 0x3F

// Zero mode commands
#define SET_ZERO_MODE 0x90
#define SET_ZERO_ZERO 0x91
#define SET_ZERO_SPEED 0x92
#define SET_ZERO_DIR 0x93
#define RETURN_ZERO 0x94

// PID/ACC/Torque
#define SET_KP_POS 0xA1
#define SET_KI_POS 0xA2
#define SET_KD_POS 0xA3
#define SET_ACC 0xA4
#define SET_TORQUE_MAXT 0xA5

// Serial Control
#define SET_EN_CRUART 0xF3
#define RUN_CONSTANT_SPEED 0xF6
#define STOP_RUNNING 0xF7
#define SAVE_CLEAR_STATUS_SET 0xFF
#define RUN_DIR_PULSES 0xFD
